input {
  http {
    port => 5044
    codec => json
  }
}

filter {
  # ECS already normalized by agent
  mutate {
    add_field => { "received_by" => "logstash" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "elkagent-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}